services:
  backend:
    build: .
    command: sh -c "cd backend && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=hackathon_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hackathon_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # No external port mapping needed - backend accesses via internal network

volumes:
  postgres_data:
